version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.x
    steps:
      - checkout

      - run:
          name: "Install Dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: "Run Tests"
          command: pytest

      - setup_remote_docker

      - run:
          name: "Build Docker Image"
          command: |
            docker build -t demonxslayer47/docker_test_sparserecommender:latest .

      - run:
          name: "Push Docker Image"
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "demonxslayer47" --password-stdin
            docker push demonxslayer47/docker_test_sparserecommender:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
